version: '3.8'

services:
  frontend:
    container_name: template
    image: template:1.0.0
    build: 
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL} # get from .env file
        - BUILD_VERSION=${BUILD_VERSION:-latest}
    volumes:
      - /app/node_modules
    ports:
      - '3000:3000'
    command: ['yarn', 'dev']
    
